name: Docker Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r build/requirements.txt
        pip install pytest requests
        
    - name: Run tests
      run: |
        cd test
        python -m pytest test_app.py -v

  docker:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build Docker image
      run: |
        cd deploy
        docker-compose build
        
    - name: Test Docker container
      run: |
        cd deploy
        docker-compose up -d
        sleep 30
        curl -f http://localhost:3206/ || exit 1
        docker-compose down
